### ISSUE TITLE
Repeating one song occasionally hangs on `v0.6.7`

### ISSUE THREAD

**Issue by hydrobeam** [tramhao/termusic#39]
When playing a single song on repeat in repeat-one mode, it doesn't go back to playing itself when it's finished and hangs just before it finishes playing (i.e., it'll sit at 3:46/3:47). I can't seem to consistently reproduce this issue for some reason. 

Also, after switching to the gst backend, the issue seems to not be present.

**Comment by tramhao** [comment]
Which file format you're listening? Thanks. Perhaps it's related to error handling in decoding in my new code for symphonia.

**Comment by tramhao** [comment]
I tested with an mp3 file for like 10 times, and it's playing ok. I found ogg file cannot repeat.

**Comment by tramhao** [comment]
I found one mp3 file that cannot repeat also. When problem happens, the progress bar is 0 - 1:40 which is a default value, means that the total_duration and progress of song is not fetched. Is it the same with your situation? Thanks.

**Comment by tramhao** [comment]
Let me explain what might happened here: 
termusic get the progress and duration from playing backend. If progress >= duration, it'll stop the current song and start next. Seems the progress in your example never reach duration, thus the program didn't proceed. A simple fix will be progress >= duration -1, but it doesn't seem the correct way.

**Comment by tramhao** [comment]
Would you please try the dev branch? I do the dirty fix by progress >= duration -1, means every track will be played 1 second less. Thanks.

**Comment by tramhao** [comment]
I think I fixed it in dd1ff7b42f0ea2c430d3ad1db4ec9b537485aec4. Please kindly try it and if it's ok I'll release a bug fix version for it. Thanks.

**Comment by hydrobeam** [comment]
Hey! Sorry for the delay, but I just upgraded to v0.11.0 under the mpv backend (which I assume has that commit), and the issue is still present.

**Comment by tramhao** [comment]
Now the play logic changed and for all backends, this problem should be solved. Please kindly check.
